
name: test

on: [push]

jobs:
  test:
    env:
      REF: ${{ github.ref }}
    run: |
      echo REF=$REF
      true

  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    run: echo Deploying
