
name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      REF: ${{ github.ref }}
    steps:
      - name: Run tests
        run: echo REF=$REF
      - run: |
          echo "::group::thegroup"
          echo "::warning :: 1"
          echo "::endgroup::"
          >&2 echo "::warning :: 2"


  deploy:
    runs-on: ubuntu-20.04
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Deploy
        run: echo Deploying
