name: Haskell-CI
on:
  - push
  - pull_request
jobs:
  linux:
    name: Haskell-CI - Linux - ${{ matrix.ghc-version }}
    runs-on: ubuntu-22.04
    timeout-minutes:
      60
    strategy:
      matrix:
        ghc-version: [9.8.2, 9.8.2, 9.6.6, 9.6.5, 9.6.4, 9.6.3, 9.6.2, 9.6.1, 9.4.8, 9.4.7, 9.4.6, 9.4.5,
                      9.4.4, 9.4.3, 9.4.2, 9.4.1, 9.2.8, 9.2.7, 9.2.6, 9.2.5, 9.2.4, 9.2.3,
                      9.2.2, 9.2.1, 9.0.2, 9.0.1, 8.10.7, 8.10.6, 8.10.5, 8.10.4, 8.10.3,
                      8.10.2, 8.10.1, 8.8.4, 8.8.3, 8.8.2, 8.8.1, 8.6.5, 8.6.4, 8.6.3, 8.6.2,
                      8.6.1, 8.4.4, 8.4.3, 8.4.2, 8.4.1, 8.2.2, 8.0.2, 7.10.3, 7.8.4, 7.6.3,
                      7.4.2, 7.4.1, 7.2.2, 7.0.4]
      fail-fast: false
    steps:
      - run: |
          echo "$HOME/.local/install/ghc/bin/" >> $GITHUB_PATH
          echo "$HOME/.local/install/cabal/bin/" >> $GITHUB_PATH
      - run: |
          ghcup nuke
          mkdir $HOME/tmp
          cd $HOME/tmp
          wget -nv https://downloads.haskell.org/~ghc/${{matrix.ghc-version}}/ghc-${{matrix.ghc-version}}-x86_64-deb11-linux.tar.xz
          tar xf ghc-${{matrix.ghc-version}}-x86_64-deb11-linux.tar.xz
          cd ghc-${{matrix.ghc-version}}-x86_64-unknown-linux
          ./configure --prefix=$HOME/.local/install/ghc
          make install
          cd $HOME/tmp
          wget -nv https://downloads.haskell.org/~cabal/cabal-install-3.10.1.0/cabal-install-3.10.1.0-x86_64-linux-deb11.tar.xz
          tar xf cabal-install-3.10.1.0-x86_64-linux-deb11.tar.xz
          rm plan.json
          mkdir -p $HOME/.local/install/cabal/bin/
          mv cabal $HOME/.local/install/cabal/bin/
      - run: |
          ghc --version
          cabal --version
