
name: test

on: [push]

jobs:
  test:
    env:
      REF: ${{ github.ref }}
    steps:
      - run: |
        echo REF=$REF
        true

  deploy:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - run: echo Deploying
