on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{steps.setup.outputs.dirs}}
    steps:
      - uses: actions/checkout@v4

      - id: setup
        run: |
          echo "dirs=$(ls foobar/ | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')"
          echo "dirs=$(ls foobar/ | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  foobarify:
    runs-on: ubuntu-latest
    needs: setup
    name: foobarify ${{matrix.dir}}
    strategy:
      matrix:
        dir: ${{fromJSON(needs.setup.dirs)}}
    steps:
      - run: echo ${{matrix.dir}}
