
name: test

on: [push]

jobs:
  test:
    env:
      REF: ${{ github.ref }}
    steps:
      - name: Run tests
        run: echo REF=$REF

  deploy:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Deploy
        run: echo Deploying
